name: Fetch FCA

on:
  schedule:
    - cron: "*/5 * * * *" # tiap 5 menit
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install deps
        run: pip install requests
      - name: Fetch FCA Data
        run: python fetch_fca.py
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add fca.json
          git commit -m "Update FCA data"
          git push
