name: Fetch FCA Data with Playwright

on:
  schedule:
    - cron: '*/5 * * * *'  # setiap 5 menit
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run fetch_fca.py
        run: python fetch_fca.py

      - name: Commit & push updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add fca.json
          git commit -m "Update FCA data" || echo "No changes to commit"
          git push
